import { getTranslation } from './utils/translation';

export const weatherCodeDescriptions: { [key: number]: string } = {
  0: getTranslation('clearSky'),
  1: getTranslation('mainlyClear'),
  2: getTranslation('partlyCloudy'),
  3: getTranslation('overcast'),
  45: getTranslation('fog'),
  48: getTranslation('depositingRimeFog'),
  51: getTranslation('lightDrizzle'),
  53: getTranslation('moderateDrizzle'),
  55: getTranslation('denseDrizzle'),
  56: getTranslation('lightFreezingDrizzle'),
  57: getTranslation('denseFreezingDrizzle'),
  61: getTranslation('slightRain'),
  63: getTranslation('moderateRain'),
  65: getTranslation('heavyRain'),
  66: getTranslation('lightFreezingRain'),
  67: getTranslation('heavyFreezingRain'),
  71: getTranslation('slightSnowFall'),
  73: getTranslation('moderateSnowFall'),
  75: getTranslation('heavySnowFall'),
  77: getTranslation('snowGrains'),
  80: getTranslation('slightRainShowers'),
  81: getTranslation('moderateRainShowers'),
  82: getTranslation('violentRainShowers'),
  85: getTranslation('slightSnowShowers'),
  86: getTranslation('heavySnowShowers'),
  95: getTranslation('slightThunderstorm'),
  96: getTranslation('thunderstormWithSlightHail'),
  99: getTranslation('thunderstormWithHeavyHail')
};

export const dayEmojis: { [key: number]: string } = {
  0: '☀️',
  1: '🌤️',
  2: '⛅',
  3: '☁️',
  45: '🌫️',
  48: '🌫️',
  51: '🌧️',
  53: '🌧️',
  55: '🌧️',
  56: '🌧️',
  57: '🌧️',
  61: '🌧️',
  63: '🌧️',
  65: '🌧️',
  66: '🌧️',
  67: '🌧️',
  71: '❄️',
  73: '❄️',
  75: '❄️',
  77: '❄️',
  80: '🌧️',
  81: '🌧️',
  82: '🌧️',
  85: '❄️',
  86: '❄️',
  95: '⛈️',
  96: '⛈️',
  99: '⛈️'
};

export const nightEmojis: { [key: number]: string } = {
  0: '🌕',
  1: '🌖',
  2: '🌗',
  3: '🌘',
  45: '🌫️',
  48: '🌫️',
  51: '🌧️',
  53: '🌧️',
  55: '🌧️',
  56: '🌧️',
  57: '🌧️',
  61: '🌧️',
  63: '🌧️',
  65: '🌧️',
  66: '🌧️',
  67: '🌧️',
  71: '❄️',
  73: '❄️',
  75: '❄️',
  77: '❄️',
  80: '🌧️',
  81: '🌧️',
  82: '🌧️',
  85: '❄️',
  86: '❄️',
  95: '⛈️',
  96: '⛈️',
  99: '⛈️'
};